### ISSUE TITLE
sass-graph dependency

### ISSUE THREAD

**Issue by alexandredoria** [11joselu/less-incremental-builder#14]
I see that package references the a sass-graph repository that does't exist anymore, as we see below on the package.json from 1.4.4 version.

```
"homepage": "https://github.com/11joselu/less-incremental-builder",
  "dependencies": {
   ....
    "sass-graph": "git+https://github.com/11joselu/sass-graph.git",
   ....
  },
```
I believe it has been forked from the https://github.com/xzyfer/sass-graph repository, and deleted from your personal repositories. Am I rigth?

**Comment by 11joselu** [comment]
[sass-graphs ](https://github.com/11joselu/sass-graph) was recovered it again
